services:
  api:
    ports:
      - "3001:3001"
    volumes:
      - ./backend/.env:/app/.env
    environment:
      - NODE_ENV=development

  frontend:
    ports:
      - "3000:3000"

  postgres:
    ports:
      - "5432:5432"
