FROM node:18-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:18-alpine
WORKDIR /app
RUN apk add --no-cache curl bash jq docker-cli && mkdir -p /app/uploads/tickets
COPY --from=deps /app/node_modules ./node_modules
COPY . .
EXPOSE 3001
