module.exports = {
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: [
    '**/__tests__/unit.test.js',
    '**/__tests__/*.test.js',
    '<rootDir>/src/middleware/*.test.js',
  ],
  testPathIgnorePatterns: ['/node_modules/', 'integration', 'docker'],
  coverageDirectory: '../../coverage/backend',
  setupFilesAfterEnv: ['<rootDir>/src/__tests__/jest.setup.js'],
  moduleDirectories: ['node_modules', '<rootDir>'],
  moduleNameMapper: {
    '^models/(.*)$': '<rootDir>/src/models/$1',
    '^services/(.*)$': '<rootDir>/src/services/$1',
  },
  maxWorkers: 1,
  verbose: true,
  forceExit: true,
  restoreMocks: true,
  watchPathIgnorePatterns: ['/node_modules/', '/coverage/'],
  testTimeout: 10000,
  collectCoverageFrom: [
    'src/**/*.js',
    '!src/**/*.test.js',
    '!src/index.js',
    '!src/__tests__/*',
    '!src/__mocks__/*',
    '!src/migrations/*',
    '!src/utils/redis.js',
    '!src/utils/logger.js',
    '!src/validators/computeNodes.js',
    '!src/validators/deployments.js',
    '!src/validators/milestones.js',
    '!src/api/compute-nodes.js',
    '!src/api/deployments.js',
    '!src/api/milestones.js',
    '!src/providers/github/api.js',
    '!src/providers/github/pr.js',
    '!src/providers/github/auth.js',
    '!src/providers/github/branch.js',
    '!src/providers/openai/index.js',
    '!src/providers/claude/index.js',
    '!src/providers/base/ProviderInterface.js',
    '!src/controllers/projectController.js',
    '!src/controllers/ticketAttachmentController.js',
    '!src/middleware/agentHeartbeat.js',
  ],
  coverageThreshold: {
    global: {
      branches: 60,
      functions: 60,
      lines: 60,
      statements: 60,
    },
  },
};
