-- Data migration: populate api_key_encrypted from existing api_key_credential_id references
--
-- This migration copies decrypted API keys from the credentials table into
-- the new api_key_encrypted column for existing provider_configs rows.
--
-- This is now automated as part of apply.js (runs after 029 schema migration).
-- No manual step required.
--
-- To verify after migration:
--   SELECT id, provider, api_key_encrypted IS NOT NULL as has_key, api_key_credential_id
--   FROM provider_configs WHERE api_key_credential_id IS NOT NULL;
